// Package reports provides daily and weekly report generation for the today app.
package reports

import (
	"fmt"
	"strings"
	"time"
)

// FormatDailyMarkdown formats a daily report as Markdown.
func FormatDailyMarkdown(report *DailyReport) string {
	var b strings.Builder

	// Header
	dateStr := report.Date.Format("Monday, January 2, 2006")
	b.WriteString(fmt.Sprintf("# Daily Report: %s\n\n", dateStr))

	// Tasks section
	b.WriteString("## Tasks\n\n")
	b.WriteString(fmt.Sprintf("- **Completed:** %d tasks\n", report.Tasks.CompletedCount))
	b.WriteString(fmt.Sprintf("- **Pending:** %d tasks\n", report.Tasks.PendingCount))
	if report.Tasks.AddedCount > 0 {
		b.WriteString(fmt.Sprintf("- **Added today:** %d tasks\n", report.Tasks.AddedCount))
	}
	if len(report.Tasks.ByProject) > 0 {
		b.WriteString(fmt.Sprintf("- **Top project:** %s (%d tasks)\n",
			report.Tasks.ByProject[0].Project, report.Tasks.ByProject[0].Count))
	}
	b.WriteString("\n")

	// Completed tasks list
	if len(report.Tasks.Completed) > 0 {
		b.WriteString("### Completed Tasks\n\n")
		for _, task := range report.Tasks.Completed {
			projectTag := ""
			if task.Project != "" {
				projectTag = fmt.Sprintf(" `%s`", task.Project)
			}
			b.WriteString(fmt.Sprintf("- [x] %s%s\n", task.Text, projectTag))
		}
		b.WriteString("\n")
	}

	// Pending tasks (limit to 10)
	if len(report.Tasks.Pending) > 0 {
		b.WriteString(fmt.Sprintf("### Pending Tasks (%d)\n\n", len(report.Tasks.Pending)))
		limit := 10
		if len(report.Tasks.Pending) < limit {
			limit = len(report.Tasks.Pending)
		}
		for i := 0; i < limit; i++ {
			task := report.Tasks.Pending[i]
			projectTag := ""
			if task.Project != "" {
				projectTag = fmt.Sprintf(" `%s`", task.Project)
			}
			b.WriteString(fmt.Sprintf("- [ ] %s%s\n", task.Text, projectTag))
		}
		if len(report.Tasks.Pending) > limit {
			b.WriteString(fmt.Sprintf("- ... and %d more\n", len(report.Tasks.Pending)-limit))
		}
		b.WriteString("\n")
	}

	// Time tracking section
	b.WriteString("## Time Tracked\n\n")
	if report.Time.Total > 0 {
		b.WriteString(fmt.Sprintf("- **Total:** %s\n", formatDurationHuman(report.Time.Total)))
		if len(report.Time.ByProject) > 0 {
			b.WriteString("- **Projects:**\n")
			for _, p := range report.Time.ByProject {
				b.WriteString(fmt.Sprintf("  - %s: %s (%.0f%%)\n",
					p.Project, formatDurationHuman(p.Duration), p.Percentage))
			}
		}
	} else {
		b.WriteString("_No time tracked today._\n")
	}
	b.WriteString("\n")

	// Habits section
	b.WriteString("## Habits\n\n")
	if len(report.Habits.Habits) > 0 {
		b.WriteString(fmt.Sprintf("- **Completion:** %d/%d (%.0f%%)\n\n",
			report.Habits.CompletedCount, report.Habits.TotalCount, report.Habits.CompletionRate))
		for _, h := range report.Habits.Habits {
			checkmark := "✗"
			if h.Done {
				checkmark = "✓"
			}
			streakInfo := ""
			if h.Streak > 1 {
				streakInfo = fmt.Sprintf(" (🔥%d)", h.Streak)
			}
			b.WriteString(fmt.Sprintf("- %s %s %s%s\n", h.Icon, h.Name, checkmark, streakInfo))
		}
	} else {
		b.WriteString("_No habits tracked._\n")
	}
	b.WriteString("\n")

	// Footer
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Generated by today on %s*\n", report.GeneratedAt.Format("2006-01-02 at 15:04")))

	return b.String()
}

// FormatWeeklyMarkdown formats a weekly report as Markdown.
func FormatWeeklyMarkdown(report *WeeklyReport) string {
	var b strings.Builder

	// Header
	startStr := report.StartDate.Format("Jan 2")
	endStr := report.EndDate.Format("Jan 2, 2006")
	b.WriteString(fmt.Sprintf("# Weekly Report: %s - %s\n\n", startStr, endStr))

	// Summary section
	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Tasks completed:** %d\n", report.Tasks.TotalCompleted))
	b.WriteString(fmt.Sprintf("- **Time tracked:** %s\n", formatDurationHuman(report.Time.Total)))
	b.WriteString(fmt.Sprintf("- **Habit completion:** %.0f%%\n", report.Habits.OverallRate))
	b.WriteString("\n")

	// Tasks by day table
	b.WriteString("## Tasks by Day\n\n")
	b.WriteString("| Day | Completed | Added |\n")
	b.WriteString("|-----|-----------|-------|\n")
	for _, day := range report.Tasks.ByDay {
		b.WriteString(fmt.Sprintf("| %s | %d | %d |\n", day.DayOfWeek, day.Completed, day.Added))
	}
	b.WriteString("\n")

	// Time by project table
	if len(report.Time.ByProject) > 0 {
		b.WriteString("## Time by Project\n\n")
		b.WriteString("| Project | Time | % |\n")
		b.WriteString("|---------|------|---|\n")
		for _, p := range report.Time.ByProject {
			b.WriteString(fmt.Sprintf("| %s | %s | %.0f%% |\n",
				p.Project, formatDurationHuman(p.Duration), p.Percentage))
		}
		b.WriteString("\n")
	}

	// Time by day
	b.WriteString("## Time by Day\n\n")
	b.WriteString("| Day | Time |\n")
	b.WriteString("|-----|------|\n")
	for _, day := range report.Time.ByDay {
		timeStr := "-"
		if day.Total > 0 {
			timeStr = formatDurationHuman(day.Total)
		}
		b.WriteString(fmt.Sprintf("| %s | %s |\n", day.DayOfWeek, timeStr))
	}
	b.WriteString("\n")

	// Habits table
	if len(report.Habits.Habits) > 0 {
		b.WriteString("## Habits\n\n")

		// Build header with day abbreviations
		header := "| Habit |"
		sep := "|-------|"
		for _, day := range report.Tasks.ByDay {
			header += fmt.Sprintf(" %s |", day.DayOfWeek[:1])
			sep += "----|"
		}
		header += " Rate |"
		sep += "------|"
		b.WriteString(header + "\n")
		b.WriteString(sep + "\n")

		// Build rows
		for _, h := range report.Habits.Habits {
			row := fmt.Sprintf("| %s %s |", h.Icon, h.Name)
			for _, done := range h.DaysCompleted {
				if done {
					row += " ✓ |"
				} else {
					row += " ✗ |"
				}
			}
			row += fmt.Sprintf(" %.0f%% |", h.CompletionRate)
			b.WriteString(row + "\n")
		}
		b.WriteString("\n")
	}

	// Streaks
	hasStreaks := false
	for _, h := range report.Habits.Habits {
		if h.Streak > 1 {
			hasStreaks = true
			break
		}
	}
	if hasStreaks {
		b.WriteString("## Streaks\n\n")
		for _, h := range report.Habits.Habits {
			if h.Streak > 1 {
				b.WriteString(fmt.Sprintf("- 🔥 %s: %d days\n", h.Name, h.Streak))
			}
		}
		b.WriteString("\n")
	}

	// Footer
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Generated by today on %s*\n", report.GeneratedAt.Format("2006-01-02 at 15:04")))

	return b.String()
}

// formatDurationHuman formats a duration in a human-readable way.
func formatDurationHuman(d time.Duration) string {
	d = d.Round(time.Minute)
	h := d / time.Hour
	d -= h * time.Hour
	m := d / time.Minute

	if h > 0 {
		if m > 0 {
			return fmt.Sprintf("%dh %dm", h, m)
		}
		return fmt.Sprintf("%dh", h)
	}
	return fmt.Sprintf("%dm", m)
}
